// File: lfpga_mac.v
// Generated by MyHDL 0.11.51
// Date:    Sun Jul  5 08:59:49 2026 UTC


`timescale 1ns/10ps

module lfpga_mac (
    clk,
    rst,
    clr,
    en,
    a,
    b,
    acc
);
// Signed multiply-accumulate: the atom of every neural network.
// Multiply narrow, accumulate wide. clr zeroes the accumulator.

input clk;
input rst;
input clr;
input en;
input signed [7:0] a;
input signed [7:0] b;
output signed [31:0] acc;
reg signed [31:0] acc;




always @(posedge clk) begin: seq
    if (rst == 1) begin
        acc <= 0;
    end
    else begin
        if (clr) begin
            acc <= 0;
        end
        else if (en) begin
            acc <= (acc + (a * b));
        end
    end
end

endmodule
